### ISSUE TITLE
Paper Link?

### ISSUE THREAD

**Issue by HerrYu123** [Cuibaby/MFIALane#1]
Hello, do you have a link to the paper?

**Comment by Cuibaby** [comment]
Thank you for your interest to our paper, our paper has just been accepted, you can visit this link https://ieeexplore.ieee.org/document/9872124  to read it, and you can also further understand our idea through our code.

**Comment by Cuibaby** [comment]
> Thank you for your interest to our paper, our paper has just been accepted, you can visit this li

**Comment by Cuibaby** [comment]
> Thank you for your interest to our paper, our paper has just been accepted, you can visit this link https://ieeexplore.ieee.org/document/9872124 to read it, and you can also further understand our idea through our code.

**Comment by HerrYu123** [comment]
Thanks!
